name: CI/CD Pipeline Básico

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  teste-basico:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Mostrar mensagem de teste
      run: echo "Olá, GitHub Actions! Este é um teste básico."

    - name: Listar arquivos no diretório
      run: ls -la
